// 365 short, original reflections — one per calendar day, cycling every year.
// Grouped loosely by month (new beginnings in January, closing the year in
// December) so the tone drifts with the seasons instead of feeling random.
// getDailyQuote() picks by day-of-year, so every visitor sees the same line
// on the same day, and it repeats on the same date next year.

export const QUOTES = [
  // January — quiet beginnings
  "A blank page is not empty. It's waiting.",
  "Start before you're ready. Readiness is a story you tell yourself.",
  "The first draft of anything is just you, being honest badly.",
  "Quiet mornings are where most good sentences are born.",
  "You don't need a new year to begin again. Today works too.",
  "Discipline is just love with a schedule.",
  "The smallest habit, kept daily, outlives the boldest plan, kept never.",
  "Write it down before the feeling decides it was never that important.",
  "Cold light through a window is still light worth noticing.",
  "Most beginnings look like nothing. That's how you know they're real.",
  "You are allowed to start over as many times as you need to.",
  "The version of you that finishes this year is built one unremarkable morning at a time.",
  "Slow is a pace, not a failure.",
  "A journal is a room where you're allowed to be unfinished.",
  "Ambition without patience is just a louder kind of giving up.",
  "The first step rarely looks like progress. Take it anyway.",
  "Some doors only open from the inside.",
  "You will not feel ready. Begin regardless.",
  "The quietest resolutions are usually the ones that survive February.",
  "Every long thing was once a short thing someone kept doing.",
  "New starts don't require applause, just attention.",
  "What you practice in private becomes who you are in public.",
  "Winter teaches patience to everything that intends to bloom.",
  "The page doesn't care how you feel about writing on it. Neither should you.",
  "Small, honest steps outrun big, borrowed ones.",
  "You are not behind. You are exactly as far along as someone who started when you did.",
  "A plan is just a guess you're willing to test.",
  "Somewhere in this ordinary week is the sentence you'll remember writing.",
  "Begin badly. Beginning well is a myth for people who never began.",
  "The first light of a new year looks the same as the last light of the old one. Keep going.",
  "Momentum is built by people who moved on the days they didn't feel like it.",

  // February — closeness and warmth
  "Love is mostly attention, paid consistently.",
  "The people who stay are rarely the ones who promised the most.",
  "Say the kind thing now. Later is not guaranteed.",
  "Warmth doesn't need an occasion.",
  "Some of the best conversations happen over the smallest cups of coffee.",
  "A short message, sent today, outweighs a long one you never send.",
  "The best company asks questions and then actually listens to the answer.",
  "Closeness isn't built in grand gestures. It's built on Tuesdays.",
  "Tell the people you love why, specifically, before you forget the reasons.",
  "A house gets warm from the people in it, not the walls.",
  "Real affection sounds a lot like ordinary conversation, said often.",
  "The quiet ones in a room are usually the ones paying the most attention.",
  "Loyalty looks like showing up on the unremarkable days.",
  "Some love stories are just two people choosing each other, repeatedly, on purpose.",
  "You can tell who someone is by what they do when nothing is being asked of them.",
  "A kind word costs nothing and is remembered for years.",
  "The best relationships have room for both silence and honesty.",
  "Grace is giving someone the benefit of the doubt you'd want for yourself.",
  "Distance shrinks for the people who bother to write.",
  "Being known is rarer, and better, than being admired.",
  "Warm rooms are made of small kindnesses, stacked.",
  "Say thank you like you mean it. People remember the difference.",
  "Even brief winters end. Keep the people who reminded you of that.",
  "Affection unspoken is affection half-given.",
  "The comfort of an old friend is that you don't have to perform for them.",
  "Every long friendship survived at least one ordinary disagreement, handled well.",
  "The best gift is usually just time, undistracted.",
  "You can love people and still need quiet. Both are true.",

  // March — growth and curiosity
  "Curiosity is the last renewable resource.",
  "Ask one more question than feels polite. That's where the story is.",
  "Growth is invisible until, suddenly, it isn't.",
  "The mind that stays curious rarely stays bored.",
  "You learn more from the question you almost didn't ask.",
  "Spring doesn't apologize for taking its time.",
  "A good question is worth more than a fast answer.",
  "Every expert was once a beginner who refused to stay embarrassed.",
  "Notice what you notice. That's the beginning of a point of view.",
  "The world rewards people who keep looking closer.",
  "Change your mind in public sometimes. It's a form of honesty.",
  "What you're curious about at twenty rarely matches what you're curious about at forty. Let it evolve.",
  "New growth is fragile. Protect it before you show it off.",
  "The best ideas arrive disguised as distractions.",
  "Study the thing that keeps interrupting your other plans. It's trying to tell you something.",
  "Roots grow in the dark before anything shows above the soil.",
  "A curious person is rarely a bitter one.",
  "Ask the obvious question. Half the room was too proud to.",
  "You don't have to know where an idea is going to follow it for a while.",
  "The green returning to the trees didn't ask permission. Neither should your next idea.",
  "Most breakthroughs are just old questions asked with new patience.",
  "Stay a student of the thing you're best at. Especially then.",
  "Wonder is underrated as a discipline.",
  "The quickest way to feel young again is to learn something badly on purpose.",
  "Every field looks impossible from outside and learnable from within.",
  "Growth prefers people who show up before they feel qualified.",
  "The right question can survive a hundred wrong answers.",
  "Spring is proof that dormant is not the same as dead.",
  "Keep a list of things you don't understand yet. It's a map, not a confession.",
  "The most interesting people are the ones still asking why.",
  "Curiosity costs you comfort and pays you back in a bigger world.",

  // April — patience and renewal
  "Rain doesn't rush and neither does anything worth growing.",
  "Some seasons of life are just for waiting well.",
  "Patience isn't passive. It's active trust in timing you can't see yet.",
  "The bud doesn't force the bloom. It just stays ready.",
  "You will not always be able to see the reason for the delay. Proceed anyway.",
  "A slow yes is still a yes.",
  "Renewal rarely announces itself. It just quietly starts again.",
  "What looks like standing still is sometimes just roots deepening.",
  "The storm passes. Build for after it, not just through it.",
  "Every long wait ends the same way: eventually.",
  "Grow at your own weather, not someone else's forecast.",
  "You can't rush a good sentence, a good friendship, or a good spring.",
  "Some things take exactly as long as they take.",
  "The patient gardener outlasts the anxious one.",
  "Renewal looks like rest before it looks like results.",
  "You are allowed to be in an in-between season without explaining it.",
  "The rain that annoys you today waters what you'll be glad for in June.",
  "Trust the process you can't yet see the end of.",
  "Not every delay is a denial.",
  "New leaves don't apologize for taking a season to arrive.",
  "The wait is doing something, even when it looks like nothing.",
  "Slow progress is still progress, measured on a longer clock.",
  "A held breath eventually has to be let out. So does a held plan.",
  "Some things bloom late and are no less beautiful for it.",
  "You plant in one season and harvest in another. Don't confuse the two.",
  "Patience is just faith stretched over time.",
  "What feels stuck may just be gathering.",
  "The calendar says April. Some parts of you are still in March. That's fine.",
  "Renewal doesn't need your permission, only your attention.",
  "Wait like it's working, because it is.",

  // May — creativity and color
  "Make the thing that only you would make.",
  "Creativity is just attention with nowhere else to be.",
  "Color the ordinary day in on purpose.",
  "The work you're proudest of later usually felt like play while you made it.",
  "You don't find your style. You keep making things until it finds you.",
  "A creative life is built from small, unglamorous Tuesdays of practice.",
  "The blank canvas isn't your enemy. Your own hesitation is.",
  "Make something today that didn't exist yesterday.",
  "Taste develops faster than skill. Keep working until skill catches up.",
  "The most original work usually starts as an honest copy of something you loved.",
  "You are allowed to make something just because it's beautiful, with no other reason.",
  "Every artist's early work is embarrassing. Make it anyway.",
  "Color exists so the ordinary can occasionally be dazzling.",
  "The world doesn't need more perfect work. It needs more honest work.",
  "Play first. Polish later.",
  "A finished, imperfect thing beats a perfect thing that never left your head.",
  "Notice the light before it noticed you back.",
  "Make for the version of you who needed this exact thing once.",
  "The muse shows up for people who are already at the desk.",
  "Some days the best creative act is simply paying attention.",
  "Your unfinished projects are not failures. They're compost for the next one.",
  "Bring color to a gray day on purpose. It counts as a skill.",
  "A photograph is just a decision about what to leave out.",
  "Make the thing you wish existed.",
  "Every masterpiece started as someone's rough draft.",
  "Creativity rewards people who show up bored and stay anyway.",
  "The work teaches you what it wants to be, if you keep listening.",
  "Choose the brave color, not just the safe one.",
  "You are the only person who can make the thing only you can make.",
  "Let this month be loud with color and quiet with doubt.",
  "Art is attention, dressed up and given somewhere to go.",

  // June — light and momentum
  "Long days reward people who use the extra light well.",
  "Momentum is easier to keep than to start. Don't stop today.",
  "Summer doesn't wait for you to feel ready for it. Neither should you.",
  "The easiest habit to keep is the one you're already mid-swing on.",
  "Light lasts longer this month. So should your effort.",
  "Move while the momentum is with you.",
  "Ease into summer, but don't ease out of the work.",
  "The days are longer. Use one extra hour for something that matters.",
  "Warm weather is a good excuse to work outside and a bad excuse to stop working.",
  "Keep the streak. It's easier to protect than to rebuild.",
  "Golden hour happens twice a day. Notice it at least once.",
  "You've built momentum. Don't spend June apologizing for it.",
  "Long light, long stride.",
  "The middle of the year is not the time to quit on January's plans.",
  "Summer rewards the people who kept showing up in the cold months.",
  "A little sunlight fixes more moods than people admit.",
  "Ride the season that wants to move. Rest comes later.",
  "The best momentum is boring: same time, same effort, most days.",
  "Half the year is behind you. Look at how far that actually is.",
  "Long evenings are a gift. Spend a few of them on the thing you keep postponing.",
  "Move like the light does — steadily, and a little longer each day.",
  "Warm days make good excuses. Don't take all of them.",
  "The middle of a project always feels slower than it is. Keep moving.",
  "Momentum compounds quietly until, one day, it's obvious.",
  "Take the walk. The light is doing something worth seeing.",
  "Some of the best ideas of the year arrive in the laziest part of summer.",
  "June rewards whoever kept a rhythm through winter.",
  "The days are generous with light. Be generous back with effort.",
  "A good streak is just a series of small yeses, repeated.",
  "Let momentum carry what discipline started.",

  // July — honesty and plain truth
  "Say the true thing, gently, but say it.",
  "An honest view, offered kindly, is a form of respect.",
  "The truth is rarely convenient and almost always worth it anyway.",
  "You don't have to be right about everything to be honest about something.",
  "Say what you actually think. The world has enough polite silence.",
  "Honesty is a habit, not a mood. Practice it on the small things too.",
  "A view worth having is a view worth stating plainly.",
  "Kindness and honesty aren't opposites. The best people manage both.",
  "The bravest sentence in any piece of writing is usually the truest one.",
  "Say the uncomfortable thing before it becomes the unspoken thing.",
  "Plain truth, said once, outlasts a polite lie repeated for years.",
  "You earn trust one honest sentence at a time.",
  "An opinion held loosely is worth more than a certainty held tightly for the wrong reasons.",
  "Tell the truth even when your voice shakes.",
  "The clearest writing usually comes from the clearest thinking, which usually comes from the most honesty.",
  "Say less, mean more, and mean it truly.",
  "A well-argued view respects the reader enough to be specific.",
  "Honesty doesn't require volume. It requires nerve.",
  "The world doesn't need your certainty. It needs your honest attempt at clarity.",
  "Disagreement, handled with respect, is a form of care.",
  "Speak plainly. Complexity is not the same as depth.",
  "The truest sentences are usually the shortest ones.",
  "Say what you saw, not what sounds impressive.",
  "An honest 'I don't know' beats a confident guess dressed up as fact.",
  "You can hold a strong view and still hold it with humility.",
  "Write the sentence you'd be embarrassed to say out loud. That's usually the true one.",
  "Plain speech is a form of respect for the reader's time.",
  "The truth doesn't need decoration, just clarity.",
  "Say it straight. People remember straight talk long after they forget the flattering version.",
  "Honest views age better than popular ones.",
  "There is courage in a well-placed, plainly stated 'no'.",

  // August — rest and stillness
  "Rest is not the opposite of productivity. It's part of it.",
  "The hottest part of the year has always been for slowing down. Let it.",
  "Stillness is not laziness. It's where the next idea gathers strength.",
  "You are allowed a season with no goals in it.",
  "A quiet afternoon, unhurried, is not a wasted one.",
  "Rest before you need it, not just after you've earned it.",
  "The work will still be there tomorrow. Take the nap.",
  "Slow, hot days are made for reading something with no deadline attached.",
  "Doing nothing, occasionally, is a discipline too.",
  "The mind needs empty space the way a room needs air.",
  "Some of the best ideas show up uninvited, during rest.",
  "You don't owe anyone constant motion.",
  "Stillness reveals what busyness was hiding from you.",
  "The heat of August has one lesson: not everything needs to be urgent.",
  "Take the slow road home once this month, on purpose.",
  "A body that never rests eventually stops asking permission to.",
  "Rest is where ambition quietly gets its second wind.",
  "You can love your work and still need a week away from it.",
  "The best decisions rarely get made in exhaustion.",
  "Let August be unproductive on purpose, at least for a week.",
  "Stillness is not the absence of progress. It's progress you can't see yet.",
  "Sit still long enough to notice what you'd otherwise rush past.",
  "Rest isn't earned. It's required.",
  "A slower pace this month will not cost you the year.",
  "The garden grows even when no one is watching it work.",
  "Give yourself the same grace in August that you'd give a tired friend.",
  "Quiet days are where the noise of the rest of the year finally settles.",
  "You are more than your output, especially this month.",
  "Rest well. The fall will ask a lot of you.",
  "Stillness has its own kind of productivity, if you let it work.",
  "Take the whole afternoon. It will still be summer when you're done.",

  // September — change and letting go
  "Some things are meant to be carried only for a season.",
  "Letting go is not losing. It's making room.",
  "Change rarely announces itself politely. Meet it anyway.",
  "The leaves that fall aren't failing. They're finishing.",
  "You can honor a season and still be glad it's ending.",
  "New chapters ask you to close old ones first.",
  "Not every ending is a loss. Some are simply completions.",
  "Growth sometimes looks like subtraction before it looks like addition.",
  "Say goodbye to the summer version of your plans without guilt.",
  "You outgrow things quietly, long before you admit it out loud.",
  "September is a soft reminder that beginnings and endings share a season.",
  "Let go of what served its purpose. Thank it, and move on.",
  "Change is easier to survive than to predict. Stop trying to predict it.",
  "The tree lets go of its leaves without apology. Take notes.",
  "A door closing quietly is still a door closing. Notice it.",
  "You are allowed to want something different than you wanted in June.",
  "Some transitions look like falling apart and are actually falling into place.",
  "Release the plan that no longer fits the person you've become.",
  "Autumn doesn't mourn summer. It simply moves forward.",
  "What you release makes room for what you actually need.",
  "Change asks for less certainty and more trust than we'd like.",
  "The best editing, in writing and in life, is knowing what to cut.",
  "You don't have to explain every ending. Some just need to happen.",
  "Falling leaves are proof that letting go can be beautiful.",
  "New seasons rarely wait for you to finish grieving the old one, so start anyway.",
  "Some habits, like some leaves, are meant to fall this month.",
  "Change is just life's way of making sure you keep paying attention.",
  "You can love a chapter and still be ready to turn the page.",
  "Letting go, done well, looks a lot like trust.",
  "The harvest only happens because something earlier was released.",

  // October — memory and golden light
  "Memory is the only time machine that actually works.",
  "Golden light makes even ordinary streets look like they remember something.",
  "The past doesn't need your permission to be beautiful in hindsight.",
  "Nostalgia is just love, remembered with better lighting.",
  "Keep the photographs. You'll need them more than you think.",
  "Some memories only make sense years after you've lived them.",
  "The light in October forgives almost everything it touches.",
  "Write it down now. Memory edits generously and not always accurately.",
  "You don't remember days. You remember light, and who was standing in it.",
  "A good memory, revisited, is a small kind of time travel.",
  "The past is a rough draft the present keeps quietly revising.",
  "Autumn light is proof that things can be dying and gorgeous at the same time.",
  "Hold on to the ordinary moments. Those are the ones you'll miss.",
  "Memory keeps the parts that mattered and loses the parts that didn't. Trust it, mostly.",
  "Some years are remembered for one golden afternoon in the middle of them.",
  "The color of the leaves this month is basically a farewell letter.",
  "You don't choose what you remember. You choose what you write down.",
  "A season ending well is a memory worth keeping.",
  "Golden hour in October apologizes for nothing and forgets nothing.",
  "The photographs you almost didn't take are usually the ones you're glad you did.",
  "Memory softens the hard parts and sharpens the good ones. That's mercy, not dishonesty.",
  "This is the month for looking back gently, not critically.",
  "Keep a record. Someday it will be the only proof it happened at all.",
  "The leaves changing color is just the year keeping a journal of its own.",
  "Some memories need distance before they make sense.",
  "October light turns even a parking lot into something worth photographing.",
  "You'll forget most days. Write down the ones you can't afford to.",
  "Nostalgia is safest in small doses and truest in specific details.",
  "A remembered kindness outlives almost everything else.",
  "This month, look back long enough to say thank you.",
  "Golden light, once seen, is hard to unsee in every October after.",

  // November — gratitude and quiet thanks
  "Gratitude is just attention pointed at what's already good.",
  "Say thank you before the moment asks you to.",
  "The smallest things are usually the ones most worth thanking someone for.",
  "A grateful mind finds more to be grateful for. It's a strange, generous loop.",
  "Notice what's working before you list what isn't.",
  "Thanks, said specifically, means more than thanks said generally.",
  "The people who showed up quietly all year deserve a loud thank you now.",
  "You can be grateful and still want more. Both can be true at once.",
  "A short thank-you note outlives most long conversations.",
  "Gratitude doesn't wait for perfect circumstances. It works with what's here.",
  "Count what stayed, not just what left.",
  "The ordinary table, the ordinary meal, the ordinary people — that's the whole point.",
  "Thankfulness is a discipline you get better at with practice, like anything else.",
  "Say what you're grateful for out loud. It sounds different than it does in your head.",
  "This year gave you more to be thankful for than your memory is currently crediting it for.",
  "A grateful life notices the quiet gifts, not just the loud ones.",
  "Thank the people who make your ordinary days better. They rarely hear it enough.",
  "Gratitude turns what you have into enough.",
  "The harvest table exists to remind you that enough is a feeling, not a number.",
  "Notice who showed up. Thank them before the year lets you forget.",
  "You are allowed to be thankful for a hard year that taught you something.",
  "Say thanks for the boring blessings too. They're doing more work than you think.",
  "Gratitude, practiced daily, is quietly one of the strongest habits there is.",
  "This month, write down five ordinary things you'd miss if they were gone.",
  "The best kind of thanks is the kind followed by action.",
  "A grateful heart is rarely a bitter one.",
  "Give thanks before you're asked to. It means more that way.",
  "You don't need a reason to be thankful today. Today is the reason.",
  "Notice the people who make cold days feel warmer. Tell them.",
  "Gratitude is the quiet twin of contentment.",

  // December — reflection and closing the year well
  "Close the year the way you'd want to open the next one: honestly.",
  "You don't need to have figured everything out to call this year a good one.",
  "Look back long enough to learn something, then look forward.",
  "The year isn't measured only by what you finished, but by what you became.",
  "Some of your best growth this year was invisible even to you.",
  "Endings deserve the same attention beginnings get.",
  "Write down what this year taught you before the next one starts talking over it.",
  "You survived every hard day so far. That's worth noting.",
  "The quiet wins count as much as the loud ones.",
  "A year well lived rarely photographs as well as it felt.",
  "Forgive yourself for the plans that didn't survive the year. Some weren't meant to.",
  "Close old chapters with gratitude, not just relief.",
  "The best year-end review asks what you learned, not just what you achieved.",
  "You changed this year, even on the days it didn't feel like it.",
  "December light is short, but it's honest about what mattered.",
  "Say a proper goodbye to this year. It deserves one.",
  "Some resolutions weren't kept because they weren't yours to begin with.",
  "The year's hardest chapter is sometimes the one you'll be most grateful for later.",
  "Take stock gently. You were doing your best with what you knew at the time.",
  "Every year ends the same way: quietly, and then all at once.",
  "The people who stayed all year are the ones worth thanking loudest.",
  "You don't have to wait for January to start again. But it's a good excuse.",
  "This year's failures were mostly just information, not verdicts.",
  "Look at how far you came from the person who started this year.",
  "A year closed with honesty sets up a year opened with clarity.",
  "The quiet close of December is its own kind of gift.",
  "Some years teach you patience. Some teach you courage. Notice which this one taught you.",
  "You made it through every version of this year that tried to stop you.",
  "Rest at the end of the year the way you'd rest at the end of a long, good day.",
  "Whatever this year was, it was yours, and that's enough reason to close it with gratitude.",
  "Here's to the ordinary days that quietly made up the whole year."
]

// Day-of-year (1-365/366), local time, so the quote flips at local midnight.
function dayOfYear(date) {
  const start = new Date(date.getFullYear(), 0, 1)
  const diff = date - start
  return Math.floor(diff / 86400000) + 1
}

export function getDailyQuote(date = new Date()) {
  const doy = dayOfYear(date)
  const index = (doy - 1) % QUOTES.length
  return { text: QUOTES[index], dayOfYear: doy, date }
}
